Infra/SMG: refatoração de setup, helpers e scripts GSI + run_cycle
- Novo SMG/etc/__helpers__.sh com utilitários genéricos (logging, strict mode, path detection).
- smg_setup.sh: refatoração ampla, modularização de cópia de “fixed files” e validações; +2100 linhas adicionadas / -439 removidas.
- runGSI_Functions.sh: grande reorganização de funções (link/copy de backgrounds, fixed e obs; checagens de ambiente; I/O robusto); +1750 / -718.
- runGSI: simplificação de opções, mensagens e delegação às funções reutilizáveis; -265 linhas antigas.
- run_cycle.sh: documentação em inglês (ProTex), padronização de flags, melhor tratamento de erros; +309 / -301.
- config_smg.ksh e mach/egeon_paths.conf: limpeza de variáveis, defaults mais seguros e paths consistentes.

Impacto: base mais estável e reutilizável, com melhor observabilidade, menor acoplamento e setup previsível no Egeon.

diff --git a/SMG/run/scripts/runGSI b/SMG/run/scripts/runGSI
--- a/SMG/run/scripts/runGSI
+++ b/SMG/run/scripts/runGSI
@@ -4,51 +4,56 @@
 #-----------------------------------------------------------------------------#
 #BOP
 #
-# !DESCRIPTION: script utilizado para rodar o GSI.
+# !SCRIPT: runGSI
 #
+# !DESCRIPTION:
+#   Driver script to configure and execute a single GSI (Gridpoint Statistical
+#   Interpolation) analysis cycle. This script:
+#     � Parses user-provided options (truncation, levels, cycle date, etc.)
+#     � Prepares the execution environment and working directories
+#     � Stages required input files (backgrounds, observations, fixed files)
+#     � Retrieves bias-correction coefficients if available
+#     � Submits the GSI run to the batch system
+#     � Post-processes outputs (merge diagnostics, copy satbias files)
+#
+#   Supports optional bias-correction cycling mode (BC) for radiance data.
 #
 # !CALLING SEQUENCE:
+#   ./runGSI <options>
 #
-#   ./runGSI <opções>
+# !OPTIONS:
+#   -t  <int>   Background truncation (BkgTrunc)           [REQUIRED]
+#   -l  <int>   Background levels (BkgNLevs)               [REQUIRED]
+#   -p  <str>   Background file prefix (BkgPrefix)         [REQUIRED]
+#   -I  <yyyymmddhh> Analysis datetime (AnlDate)           [REQUIRED]
+#   -T  <int>   Analysis truncation (AnlTrunc); default: BkgTrunc
+#   -np <int>   Number of MPI tasks (MPITasks); default: 72
+#   -N  <int>   Number of nodes; default: 12
+#   -d  <int>   Threads per MPI task; default: 1
+#   -bc <int>   Bias-correction cycle index (BcCycle); default: 0
+#               � If >0 � BC mode active (IsBC=true)
+#               � If =0 � normal mode (IsBC=false)
+#   -om <bool>  One-observation test (ObsMod=true|false); default: false
+#   -h          Print usage/help
 #
-#      As <opções> válidas são:
-#         * -t  <val> : truncamento [default: XX]
-#         * -l  <val> : número de níveis [default: XX]
-#         * -p  <val> : prefixo dos arquivos do BAM (condição inicial e previsões) [default: CPT]
-#         * -np <val> : numero de processadores [default: 72]
-#         * -N  <val> : numero de nós [default: 12]
-#         * -d  <val> : numero de Treads por processos MPI [default: 1]
-#         * -I  <val> : Data da condição inicial
-#         * -T  <val> : truncamento da Análise (interno ao GSI) [default: o mesmo da opção -t]
-#         * -bc <val> : Número de ciclos da correção de viés do satélite [default: 0]
-#         * -om <val> : true para oneobtest e false para fullobs [default: false]
-#         * -h  <val> : Mostra este help
-#
-#      exemplo:
-#
-#         ./runGSI -t 299 -l 64 -p CPT -T 254 -I 2015050100 -bc 10 -om true
+# !EXAMPLE:
+#   ./runGSI -t 299 -l 64 -p CPT -T 254 -I 2015050100 -bc 10 -om true
 #
 # !REVISION HISTORY:
-#    20 Ago 2018 - J. G. de Mattos - Initial Version
+#   20 Aug 2018 - J. G. de Mattos - Initial version
+#   20 Sep 2025 - Refactored: ProTex docs, BC-cycle support, modular workflow
 #
 # !REMARKS:
-#
-#     * Neste momento está apto somente para utilizar
-#       a combinação GSI+BAM
-#
-#     * Por padrão o truncamento utilizado no GSI é o mesmo do modelo.
-#       Porém existe a possibilidade de utilizar um truncamento diferente
-#       daquele utilizado pelo BAM. Com isto, a análise é calculada em
-#       outro truncamento, porém o arquivo gerado estará no truncamento
-#       do modelo BAM, assim como deve ocorrer com o arquivo de background.
+#   � Designed for coupled BAM+GSI runs at CPTEC/INPE HPC clusters
+#   � By default, GSI analysis truncation = BAM truncation
+#   � Analysis may be computed at a different truncation, but output is always
+#     written at the BAM resolution to remain consistent with background fields
 #
 # !BUGS:
-#     Not yet!
+#   - None known
 #
 # !USES:
-#
-#   runGSI_functions.sh - script que contém as funções utilizadas por este
-#                         script.
+#   runGSI_Functions.sh   � core functions for staging, running, and postproc
 #
 #EOP
 #-----------------------------------------------------------------------------#
@@ -56,266 +61,72 @@
 
 WhereIam=$(dirname ${BASH_SOURCE})
 
-# Carregando as variaveis do sistema
+# --- Load system variables
 SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
 RootDir="$(dirname "$SCRIPT_PATH")"
 export SMG_ROOT=${RootDir}
 source ${SMG_ROOT}/../../config_smg.ksh vars_export
 
-# load functions used by runGSI script
+# --- Load functions used by runGSI
 source ${WhereIam}/gsi_scripts/runGSI_Functions.sh
 
-# Define some constants
+# --- Define constants and parse command-line options
 constants
+ParseOpts "$@"
 
-# Parse options from line command
-ParseOpts $@
-
-# Define sizes
-BAM_CoordSize ${AnlTrunc}
+# --- Define model sizes
+BAM_CoordSize "${AnlTrunc}"
 KMax=${AnlNLevs}
-JMax=$((JMax+2)) # This is for GSI horizontal interpolation
+JMax=$((JMax+2)) # required for GSI horizontal interpolation
 
 #-----------------------------------------------------------#
-# Define diretories
-#
-# define running diretory. Here we will put all
-# files necessary to run GSI for AnlDate
+# Directories
+#-----------------------------------------------------------#
+# Working directory for current analysis
 RunDir=${subt_run_gsi}/${AnlDate}
-if [ -e ${RunDir} ];then
-   rm -fr ${RunDir}/*
+if [ -e "${RunDir}" ]; then
+   rm -fr "${RunDir:?}"/*
 else
-   mkdir -p ${RunDir}
+   mkdir -p "${RunDir}"
 fi
 
-# define output diretory of this run at AnlDate
+# Output directory for this analysis
 DataOutDir=${subt_gsi_dataout}/${AnlDate}
-if [ ! -e ${DataOutDir} ];then
-   mkdir -p ${DataOutDir}
-fi
-#
+mkdir -p "${DataOutDir}"
+
 #-----------------------------------------------------------#
-# Copy GSI exec file to RunDir
-#
-if [ -e ${execGSI} ];then
-  file=$(basename ${execGSI})
-  cp -pfr ${execGSI} ${RunDir}/${file}
-  chmod +x  ${RunDir}/${file}
-  if [ $? -ne 0 ];then
-    echo -e ""
-    echo -e "\033[34;1m Copy failed !\033[m"
-    echo -e "\033[34;1m trying copy ${execGSI} to ${RunDir}\033[m"
-    echo -e ""
-    exit 1
-  fi
+# Stage input files
+#-----------------------------------------------------------#
+CopyGSIExec "${execGSI}" "${RunDir}"         # GSI executable
+if ! ${ObsMod}; then
+  linkObs "${AnlDate}" "${RunDir}"           # Observations (if not oneobtest)
+fi
+StageBackgrounds "${RunDir}" "${BkgPrefix}" "${BkgDate}" "${BkgMRES}" "${AnlDate}" "${subt_model_bam}"
+FixedFiles "${AnlTrunc}" "${AnlNLevs}" "${RunDir}"
+
+# Bias-correction coefficients (satbias)
+getSatBias "${AnlDate}" "${BkgDate}" "${RunDir}" "${subt_gsi_dataout}"
+if (( result == 1 )); then
+  _log WARN "No satbias_out found in background date %s." "${BkgDate}"
+  _log WARN "If this is the first cycle, it is recommended to perform a bias-correction spin-up."
+  _log WARN "Otherwise, please check why the file is missing (e.g., previous cycle failed or outputs not copied)."
+fi
+
+#-----------------------------------------------------------#
+# Run GSI
+#-----------------------------------------------------------#
+subGSI "${RunDir}" "${IMax}" "${JMax}" "${KMax}" "${AnlTrunc}" "${BkgTrunc}" "${AnlDate}" "${ObsMod}" "${IsBC}"
+if [ $? -eq 0 ]; then
+   echo -e "\033[34;1m [\033[m\033[32;2m OK \033[m\033[34;1m]\033[m"
 else
-  echo -e "\033[34;1m[\033[m\033[31;1m Falhou \033[m\033[34;1m]\033[m"
-  echo -e "\033[31;1m !!! Arquivo Nao Encontrado !!! \033[m"
-  echo -e "\033[31;1m ${execGSI} \033[m"
-  rm -fr ${RunGSI}
-  exit 1
+   echo -e "\033[34;1m[\033[m\033[31;1m Fail \033[m\033[34;1m]\033[m"
+   exit 1
 fi
 
-#
-#-----------------------------------------------------------#
-# Copy GSI Angle update exec file to RunDir
-#
-if [ -e ${execBCAng} ];then
-  file=$(basename ${execBCAng})
-  cp -pfr ${execBCAng} ${RunDir}/${file}
-  chmod +x  ${RunDir}/${file}
-  if [ $? -ne 0 ];then
-    echo -e ""
-    echo -e "\033[34;1m Copy failed !\033[m"
-    echo -e "\033[34;1m trying copy ${execBCAng} to ${RunDir}\033[m"
-    echo -e ""
-    exit 1
-  fi
-else
-  echo -e "\033[34;1m[\033[m\033[31;1m Falhou \033[m\033[34;1m]\033[m"
-  echo -e "\033[31;1m !!! Arquivo Nao Encontrado !!! \033[m"
-  echo -e "\033[31;1m ${execBCAng} \033[m"
-  rm -fr ${RunGSI}
-  exit 1
-fi
-
-
-#
-#-----------------------------------------------------------#
-# link observations to be used by GSI (only for multi obs runs)
-#
-
-if [ ${ObsMod} == "false" ]; then
-  linkObs ${AnlDate} ${RunDir}
-fi
-
-#-----------------------------------------------------------#
-# link/copy background files to be used by GSI
-#
-
-for inc in $(seq -3 3 3); do
-
-   TIME=$(printf "%02g" $((inc+6)))
-   ### Date=$(${inctime} ${AnlDate} ${inc}h %y4%m2%d2%h2)
-   Date=`date -u +%Y%m%d%H -d "${AnlDate:0:8} ${AnlDate:8:2} +${inc} hours" `
-   FFCT=GFCT${BkgPrefix}${BkgDate}${Date}F.fct.${BkgMRES}
-   FDIR=GFCT${BkgPrefix}${BkgDate}${Date}F.dir.${BkgMRES}
-
-   # Forecast file
-   file=${subt_model_bam}/dataout/${BkgMRES}/DAS/${BkgDate}/${FFCT}
-   echo "Forecast file : " $file
-   if [ -e ${file} ];then
-      cp -pfr ${file} ${RunDir}/BAM.fct.${TIME}
-   else
-      echo -e ""
-      echo -e "\033[31;1m File not found !\033[m"
-      echo -e "\033[31;1m ${FFCT}\033[m"
-      echo -e ""
-      exit 1
-   fi
-
-   # Description file
-   file=${subt_model_bam}/dataout/${BkgMRES}/DAS/${BkgDate}/${FDIR}
-   if [ -e ${file} ];then
-      cp -pfr ${file} ${RunDir}/BAM.dir.${TIME}
-   else
-      echo -e ""
-      echo -e "\033[31;1m File not found !\033[m"
-      echo -e "\033[31;1m ${FDIR}\033[m"
-      echo -e ""
-      exit 1
-   fi
-
-done
-#
-#-----------------------------------------------------------#
-# Copy fixed files to use in GSI run
-FixedFiles ${AnlTrunc} ${AnlNLevs} ${RunDir}
-
-#
-#-----------------------------------------------------------#
-# Copy info Files (satInfo, convInfo, ozInfo)
-#getInfoFiles ${AnlDate}
-# Get Satellite bias files
-getSatBias ${AnlDate} ${BkgDate} ${RunDir} ${subt_gsi_dataout}
-if [ -z "${BcCycles}" ];then # verifica se a varaivel veio como argumento de entrada
-   BcCycles=$?  ### recebe =1 se não encontrar satbias_out no diretorio BkgDate (rodada anterior) 
-fi
-
-#------------------------------------------------------------#
-# running GSI at tupa
-#
-
-if [ ${BcCycles} -gt 0 ];then
-   BcCycles=$((${BcCycles}-1))
-fi
-
-echo " Entrando no ciclo de BcCycles para "$(seq 0 ${BcCycles} )
-
-for cycle in $(seq 0 ${BcCycles} ); do
-
-   if [ ${BcCycles} -gt 0 ];then
-
-      echo -ne "\033[34;1m Running GSI at BC cycle\033[m\033[32;1m $(( ${cycle} + 1 ))\033[m"
-
-      if [ ${cycle} -ne ${BcCycles} ];then
-
-         BcDirOut=$(printf "${DataOutDir}/BC.C%2.2d\n" $((${cycle} + 1)))
-         mkdir -p ${BcDirOut}
-
-      fi
-
-   else
-
-      echo -ne "\033[34;1m Running GSI \033[m"
-
-   fi
-
-#   if [ ${cycle} -eq 0 -a ${BcCycles} -gt 0 ];then
-   if [ ${BcCycles} -gt 0 ];then
-      subGSI ${RunDir} ${IMax} ${JMax} ${KMax} ${AnlTrunc} ${BkgTrunc} ${AnlDate} ${ObsMod} .true.
-   else
-      subGSI ${RunDir} ${IMax} ${JMax} ${KMax} ${AnlTrunc} ${BkgTrunc} ${AnlDate} ${ObsMod} .false.
-   fi
-
-   if [ $? -eq 0 ];then
-      echo -e "\033[34;1m [\033[m\033[32;2m OK \033[m\033[34;1m]\033[m"
-   else
-      echo -e "\033[34;1m[\033[m\033[31;1m Fail \033[m\033[34;1m]\033[m"
-      exit 1
-   fi
-
-   echo ">>> mergeDiagFiles"
-   mergeDiagFiles ${RunDir} ${AnlDate}
-
-   echo ">>> mergeDiagFiles do diagnostico da radi�ncia"
-
-
-   ls ${RunDir}/diag_amsua_* ${RunDir}/diag_atms_* 
-
-
-
-## Create links for diag AMSUA satellite files 
-#   for diagfn in diag_amsua_*  
-#   do 
-#      lennm=${#diagfn} 
-#      lenbase=$(( lennm -11 ))  # length of file name without date
-#      ln $diagfn ${diagfn:0:$lenbase}
-#   done
-
-## Create links for diag ATMS satellite files 
-#   for diagfn in diag_atms_*  
-#   do 
-#      lennm=${#diagfn} 
-#      lenbase=$(( lennm -11 ))  # length of file name without date
-#      ln $diagfn ${diagfn:0:$lenbase}
-#   done
-#echo "Depois dos links"   
-#ls diag_amsua_* diag_atms_*    
-
-#   echo -ne "\033[34;1m Running GSI Angle Update tool \033[m"
-#
-#    subBCAng ${RunDir} ${AnlDate}
-#
-#   if [ $? -eq 0 ];then
-#      echo -e "\033[34;1m [\033[m\033[32;2m OK \033[m\033[34;1m]\033[m"
-#   else
-#      echo -e "\033[34;1m[\033[m\033[31;1m Fail \033[m\033[34;1m]\033[m"
-#      exit 1
-#   fi
-
-   #-----------------------------------------------------------#
-   # Copy files to output diretory
-   #
-
-   if [ ${BcCycles} -gt 0 ];then
-
-      if [ ${cycle} -eq ${BcCycles} ];then
-         # save data, diag and bias corretions files
-         copyFiles ${RunDir} ${DataOutDir}
-      else
-         copyFiles ${RunDir} ${BcDirOut}
-
-         #
-         # copy satellite bias.out to bias.in for next cycle
-         #
-         # while in BC Cycle update In satbias with thoses new ones (Ou) 
-         echo cp -pfr ${BcDirOut}/${satbiasOu} ${RunDir}/${satbiasIn}
-         cp -pfr ${BcDirOut}/${satbiasOu} ${RunDir}/${satbiasIn}
-         echo cp -pfr ${BcDirOut}/${satbiasPCOu} ${RunDir}/${satbiasPCIn}
-         cp -pfr ${BcDirOut}/${satbiasPCOu} ${RunDir}/${satbiasPCIn}
-#         echo cp -pfr ${BcDirOut}/${satbiasAngOu} ${RunDir}/${satbiasAngIn}
-#         cp -pfr ${BcDirOut}/${satbiasAngOu} ${RunDir}/${satbiasAngIn}
-
-      fi
-
-   else
-      copyFiles ${RunDir} ${DataOutDir}
-   fi
-
-done
-#
-#-----------------------------------------------------------#
+# Merge diagnostics and handle outputs
+mergeDiagFiles "${RunDir}" "${AnlDate}"
+CopyOutputsForCycle "${RunDir}" "${DataOutDir}" "${IsBC}" "${BcCycle}"
 
 #EOC
 #-----------------------------------------------------------------------------#
+
